### ISSUE TITLE
Existing action after triggering Test Project

### ISSUE THREAD

**Issue by Pretoors-Ruben** [Mahan-F/test-project-action#1]
Any way that you can add a parameter to exit the job running on GitHub upon triggering the job on Test Project?

When canceling the action on GitHub it still runs the job on Test Project, would be great if you can implement that to decrease the amount of time the action is running and prevent over usage on GitHub.

**Comment by Mahan-F** [comment]
Hi, so you want a parameter which will make the GitHub action to not wait for the tests to complete?

I can look into adding it and I see why you want it as the tests can take some time to complete usually but unfortunately this will lose the benefit of being properly used in a CI/CD pipeline as the tests failing will not stop the CD pipeline that comes after.

**Comment by Pretoors-Ruben** [comment]
Hi, yes that is correct.

Much appreciated, we only need it to give the option to only trigger the Test Project and if needed to be switch between the two.

**Comment by Mahan-F** [comment]
Hi @Pretoors-Ruben, I just released a new version `1.2.0` which has a new parameter `wait_for_tests`. 
Setting this parameter to `false` should do what you want. Let me know if it's all good.

**Comment by Pretoors-Ruben** [comment]
Hi @Mahan-F , thank you so much.

Will give it a test run and let you know

**Comment by Pretoors-Ruben** [comment]
It looks like it is still checking the status of the running jobs with the wait_for_tests set to false.

**Comment by Mahan-F** [comment]
Sorry @Pretoors-Ruben, I got busy with work and forgot about this issue.

I just came across it now and it should be fixed in `1.2.1`. I tested it with my setup and it does not wait for the tests.
